DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS records;

CREATE TABLE tasks (
  ID            BIGINT      NOT NULL AUTO_INCREMENT,
  NAME          VARCHAR(50) NOT NULL,
  DESCRIPTION   VARCHAR(200),
  COLOR         VARCHAR(10) NOT NULL,
  LAST_MODIFIED TIMESTAMP   NOT NULL,
  IS_ACTIVE     BOOLEAN     NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE records (
  ID                BIGINT    NOT NULL AUTO_INCREMENT,
  TASK_ID           BIGINT    NOT NULL,
  START_DATETIME    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  END_DATETIME      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATION_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  SYNCH_DATETIME    TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (TASK_ID) REFERENCES tasks (ID)
);


ALTER TABLE tasks ADD UNIQUE UNIQUE_INDEX(NAME, IS_ACTIVE);
ALTER TABLE records ADD COLUMN IS_ACTIVE BOOLEAN NOT NULL;
ALTER TABLE records ADD COLUMN UUID VARCHAR(36) NOT NULL UNIQUE;