DROP TABLE IF EXISTS TASKS;
DROP TABLE IF EXISTS RECORDS;

CREATE TABLE TASKS (
  ID            BIGINT      NOT NULL AUTO_INCREMENT,
  NAME          VARCHAR(50) NOT NULL,
  DESCRIPTION   VARCHAR(200),
  COLOR         VARCHAR(10) NOT NULL,
  LAST_MODIFIED TIMESTAMP   NOT NULL,
  IS_ACTIVE     BOOLEAN     NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE RECORDS (
  ID                BIGINT    NOT NULL AUTO_INCREMENT,
  TASK_ID           BIGINT    NOT NULL,
  START_DATETIME    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  END_DATETIME      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATION_DATETIME TIMESTAMP,
  SYNCH_DATETIME    TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID)
);


ALTER TABLE TASKS ADD UNIQUE UNIQUE_INDEX(NAME, IS_ACTIVE);
ALTER TABLE TASKS ADD COLUMN UUID VARCHAR(36) UNIQUE NOT NULL;
ALTER TABLE RECORDS ADD COLUMN IS_ACTIVE BOOLEAN NOT NULL;
ALTER TABLE RECORDS ADD COLUMN UUID VARCHAR(36) NOT NULL UNIQUE;
