DROP TABLE IF EXISTS TASKS;
DROP TABLE IF EXISTS RECORDS;

CREATE TABLE TASKS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(200),
  COLOR VARCHAR(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE RECORDS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TASK_ID BIGINT NOT NULL,
  START_DATETIME TIMESTAMP NOT NULL,
  END_DATETIME TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID)
);

